In [2]:
dir_path = '/content/drive/MyDrive/each-100-data'

In [3]:
import torch
import torchvision
from torchvision.io import read_image
from torch.utils.data import Dataset, DataLoader
import pandas as pd
import os
import natsort
import csv

In [ ]:
dir_lists = natsort.natsorted(os.listdir(dir_path))
# print(dir_lists)

f = open(dir_path+'/train.csv', 'w', encoding='utf-8')
wr = csv.writer(f)
for _label in dir_lists:
    file_dir = os.path.join(dir_path, _label)
    label = _label[4:]
    print(label)
    file_list = os.listdir(file_dir)
    
    for file in file_list:
        file_path = os.path.join(file_dir, file)
        wr.writerow([file_path, label])
f.close()

shirts
top
nit-sweater-gardigan
bottom
onepiece-jumpsuit
formaljacket-schooljacket
vest
jacket-jumper
coat-trenchcoat
paddingvest
padding


In [7]:
class SimpleDataset(Dataset):
    def __init__(self, t):
        self.t = t

    def __len__(self):
        return self.t

    def __getitem__(self, idx):
        return torch.LongTensor([idx])
        
# if __name__ == "__main__":
#     dataset = SimpleDataset(t=14)
#     dataloader = DataLoader(dataset=dataset,
#                             batch_size=5,
#                             shuffle=True,
#                             drop_last=True)

#     for epoch in range(2):
#         print(f"epoch : {epoch} ")
#         for batch in dataloader:
#             print(batch)

if __name__ == "__main__":
    dataset = SimpleDataset(t=5)
    dataloader = DataLoader(dataset=dataset,
                            batch_size=2,
                            shuffle=True,
                            drop_last=False)

    for epoch in range(2):
        print(f"epoch : {epoch} ")
        for batch in dataloader:
            print(batch)

epoch : 0 
tensor([[4],
        [3]])
tensor([[0],
        [1]])
tensor([[2]])
epoch : 1 
tensor([[0],
        [2]])
tensor([[1],
        [3]])
tensor([[4]])


In [3]:
torch.randperm(4)

tensor([0, 1, 3, 2])

In [8]:
index_array = torch.randperm(5)
# [1, 4, 0, 2, 3]
index = index_array[:batch_size]
# [1, 4]
data_list = []
for i in range(index.size(0)):
	data_list.append(dataset(index[i]))
# data_list : [tensor[1], tensor[4]]
batch = torch.stack(data_list, dim=0)

print(batch)
# [[1], [4]]

NameError: ignored

In [9]:
from sklearn.datasets import load_iris # 샘플 데이터 로딩
from sklearn.model_selection import train_test_split

# load sample
dataset = load_iris()

data = dataset['data']
target = dataset['target']

# train_test_split
x_train, x_valid, y_train, y_valid = train_test_split(data, target, test_size=0.2, shuffle=True, stratify=target, random_state=34)

In [10]:
type(dataset)

sklearn.utils._bunch.Bunch

In [11]:
type(data)

numpy.ndarray

In [5]:
import glob
import torch
from torchvision import transforms
from PIL import Image
from torch.utils.data import Dataset, DataLoader


class shirtsbottomDataset(Dataset):
    def __init__(self, path, train=True, transform=None):
        self.path = path
        if train:
            self.shirts_path = path + '/G01-shirts'
            self.bottom_path = path + '/G04-bottom'
        else:
            self.shirts_path = path + '/cat/test'
            self.bottom_path = path + '/dog/test'
        
        self.shirt_img_list = glob.glob(self.shirts_path + '/*.png')
        self.bottom_img_list = glob.glob(self.bottom_path + '/*.png')

        self.transform = transform

        self.img_list = self.shirt_img_list + self.bottom_img_list
        self.class_list = [0] * len(self.shirt_img_list) + [1] * len(self.bottom_img_list) 
    
    def __len__(self):
        return len(self.img_list)
    
    def __getitem__(self, idx):
        img_path = self.img_list[idx]
        label = self.class_list[idx]
        img = Image.open(img_path)

        if self.transform is not None:
            img = self.transform(img)

        return img, label

if __name__ == "__main__":
    transform = transforms.Compose(
        [
            transforms.ToTensor(),
        ]
    )

    dataset = shirtsbottomDataset(path=dir_path, train=True, transform=transform)
    dataloader = DataLoader(dataset=dataset,
                        batch_size=2,
                        shuffle=True,
                        drop_last=False)

    for epoch in range(2):
        print(f"epoch : {epoch} ")
        for batch in dataloader:
            img, label = batch
            print(img.size(), label)

epoch : 0 
torch.Size([2, 4, 1472, 2560]) tensor([0, 0])
torch.Size([2, 4, 1472, 2560]) tensor([0, 0])
torch.Size([2, 4, 1472, 2560]) tensor([1, 0])


RuntimeError: ignored

In [ ]:
class catdogDataset(Dataset):
    def __init__(self, path, train=True, transform=None):
        self.path = path
        if train:
            self.cat_path = path + '/cat/train'
            self.dog_path = path + '/dog/train'
        else:
            self.cat_path = path + '/cat/test'
            self.dog_path = path + '/dog/test'
        
        self.cat_img_list = glob.glob(self.cat_path + '/*.png')
        self.dog_img_list = glob.glob(self.dog_path + '/*.png')

        self.transform = transform

        self.img_list = self.cat_img_list + self.dog_img_list

        self.Image_list = []  # 바뀐부분!!!!!!!
        for img_path in self.img_list:  # 바뀐부분!!!!!!!
            self.Image_list.append(Image.open(img_path))  # 바뀐부분!!!!!!!

        self.class_list = [0] * len(self.cat_img_list) + [1] * len(self.dog_img_list) 
    
    def __len__(self):
        return len(self.img_list)
    
    def __getitem__(self, idx):
        img = self.Image_list[idx]  # 바뀐부분!!!!!!!
        label = self.class_list[idx]

        if self.transform is not None:
            img = self.transform(img)

        return img, label